// ===== 編集欄 1 / 2: PROJECTカード =====
// 新サービスをReleaseしたら、PROJECT-CARD-RULES.mdの「PROJECT入力テンプレート」を使って1件追加します。
// RELEASEお知らせはこのデータから自動生成されるため、manualNewsには重複して追加しません。
const projects = [
  {name:'Awasero Music',url:'https://studio-rizi.pages.dev/projects/awasero-music/',repository:'https://github.com/oriyu90/awasero-music',releaseDate:'2026.08.19',releaseVersion:'v1.0.0',releaseSource:'github-release',code:'AM',description:{ja:'鼻歌を編集できる楽譜とMIDIへ変換。',en:'Turn humming into editable scores and MIDI.',zh:'将哼唱转换为可编辑乐谱与 MIDI。',pt:'Transforme melodias cantadas em partituras e MIDI.'},platforms:['macOS'],color:'lime'},
  {name:'EasyRoo',url:'https://studio-rizi.pages.dev/projects/easyroo/',repository:'https://github.com/oriyu90/EasyRoo',releaseDate:'2026.07.22',releaseVersion:'v1.0',releaseSource:'github-release',code:'ER',description:{ja:'ローカルLLMで日々の作業を自動実行。',en:'Automate daily work with a local LLM.',zh:'使用本地 LLM 自动执行日常任务。',pt:'Automatize tarefas diárias com um LLM local.'},platforms:['macOS'],color:'blue'},
  {name:'Fcam pro',url:'https://studio-rizi.pages.dev/projects/fcam-pro/',repository:'https://github.com/oriyu90/fcam-pro',announceRelease:true,releaseDate:'2026.09.04',releaseVersion:'v1.0.0',releaseSource:'github-release',code:'FC',description:{ja:'マニュアル操作と多レンズ対応の本格カメラ。',en:'A pro camera with manual controls and real lenses.',zh:'支持手动控制与多镜头的专业相机。',pt:'Câmera profissional com controles manuais e lentes.'},platforms:['Android'],color:'green'},
  {name:'Humi',url:'https://studio-rizi.pages.dev/projects/humi/',repository:'https://github.com/oriyu90/humi',releaseDate:'2026.09.04',releaseVersion:'v1.5.0',releaseSource:'github-release',code:'HM',description:{ja:'ターミナルをタイルで並べる macOS アプリ。',en:'Arrange terminal sessions as tiles on macOS.',zh:'把终端会话平铺排列的 macOS 应用。',pt:'Organize sessões de terminal em blocos no macOS.'},platforms:['macOS'],color:'lime'},
  {name:'Kizi',url:'https://kizi.pages.dev/',repository:'https://github.com/oriyu90/kizi',releaseDate:'2026.08.19',releaseVersion:'',releaseSource:'repository-created',code:'KZ',description:{ja:'開発やAIについて発信する記事メディア。',en:'Articles about software development and AI.',zh:'分享软件开发与 AI 的文章媒体。',pt:'Artigos sobre desenvolvimento e inteligência artificial.'},platforms:['Web'],color:'paper'},
  {name:'MCS Manager',url:'https://studio-rizi.pages.dev/projects/mcs-manager/',repository:'https://github.com/oriyu90/MCS-Manager',releaseDate:'2026.08.30',releaseVersion:'v1.1.0',releaseSource:'github-release',code:'MC',description:{ja:'Minecraftサーバーを一か所で管理。',en:'Manage Minecraft servers from one place.',zh:'在一个界面管理 Minecraft 服务器。',pt:'Gerencie servidores Minecraft em um só lugar.'},platforms:['macOS'],color:'green'},
  {name:'MD Viewer Pro',url:'https://studio-rizi.pages.dev/projects/md-viewer-pro/',repository:'https://github.com/oriyu90/MD-Viewer-Pro',announceRelease:true,releaseDate:'2026.04.20',releaseVersion:'1.0.1',releaseSource:'github-release',code:'MD',description:{ja:'Markdownを閲覧・編集し、PDFやHTMLへ書き出し。',en:'View and edit Markdown, then export PDF or HTML.',zh:'查看和编辑 Markdown，并导出为 PDF 或 HTML。',pt:'Veja e edite Markdown e exporte em PDF ou HTML.'},platforms:['macOS'],color:'paper'},
  {name:'Media Master',url:'https://studio-rizi.pages.dev/projects/media-master/',repository:'https://github.com/oriyu90/media-master',releaseDate:'2026.08.18',releaseVersion:'v0.1.0',releaseSource:'github-release',code:'MM',description:{ja:'写真・音楽・書類を一つにまとめて管理。',en:'Manage photos, music, and documents together.',zh:'统一管理照片、音乐与文档。',pt:'Gerencie fotos, músicas e documentos juntos.'},platforms:['Android'],color:'blue'},
  {name:'MLXBar',url:'https://studio-rizi.pages.dev/projects/mlx-bar/',repository:'https://github.com/oriyu90/mlx-bar',releaseDate:'2026.09.02',releaseVersion:'v1.9.1',releaseSource:'github-release',code:'MX',description:{ja:'MacのローカルAIをメニューバーから。',en:'Local AI for Mac, right from the menu bar.',zh:'从菜单栏使用 Mac 本地 AI。',pt:'IA local no Mac, direto pela barra de menus.'},platforms:['macOS'],color:'paper'},
  {name:'Pine Chat',url:'https://studio-rizi.pages.dev/projects/pine-chat/',repository:'https://github.com/oriyu90/PineChat',releaseDate:'2026.08.18',releaseVersion:'v1.0.0',releaseSource:'github-release',code:'PC',description:{ja:'自立思考型のローカルAIエージェント。',en:'An autonomous local AI agent for macOS.',zh:'自主思考型本地 AI 智能体。',pt:'Um agente de IA local e autônomo.'},platforms:['macOS'],color:'green'},
  {name:'Tango pro',url:'https://studio-rizi.pages.dev/projects/tango-pro/',repository:'https://github.com/oriyu90/Tango-pro',releaseDate:'2026.08.22',releaseVersion:'v2.1.0',releaseSource:'github-release',code:'TP',description:{ja:'自分のCSVで続けられる単語帳アプリ。',en:'A vocabulary app built around your own CSV.',zh:'使用自己的 CSV 持续学习单词。',pt:'Um app de vocabulário feito para o seu CSV.'},platforms:['Web','Android','macOS'],color:'lime'},
  {name:'Vocello JP',url:'https://studio-rizi.pages.dev/projects/vocello-jp/',repository:'https://github.com/oriyu90/vocello-jp',releaseDate:'2026.08.18',releaseVersion:'v2.4.0-jp.1',releaseSource:'github-release',code:'VO',description:{ja:'Macで完結する日本語AI音声スタジオ。',en:'A Japanese AI voice studio that stays on Mac.',zh:'完全在 Mac 本地运行的日语 AI 语音工作室。',pt:'Estúdio de voz japonesa com IA, local no Mac.'},platforms:['macOS'],color:'blue'},
  {name:'Volume Routine',url:'https://studio-rizi.pages.dev/projects/volume-routine/',repository:'https://github.com/oriyu90/volume-routine',releaseDate:'2026.06.20',releaseVersion:'v1.1.0',releaseSource:'github-release',code:'VR',description:{ja:'時間とWi-FiでAndroid音量を自動化。',en:'Automate Android volume by time and Wi-Fi.',zh:'按时间和 Wi-Fi 自动调整 Android 音量。',pt:'Automatize o volume do Android por hora e Wi-Fi.'},platforms:['Android'],color:'lime'},
  {name:'WAKARU',url:'https://studio-rizi.pages.dev/projects/wakaru/',repository:'https://github.com/oriyu90/WAKARU',releaseDate:'2026.09.03',releaseVersion:'v0.0.4',releaseSource:'github-release',code:'WK',description:{ja:'資料を根拠つきで「わかる」に変える。',en:'Turn documents into cited understanding.',zh:'将资料转化为带有依据的理解。',pt:'Transforme documentos em entendimento com fontes.'},platforms:['macOS'],color:'paper'}
].map(project => ({
  announceRelease: true,
  ...project
}));

// ===== 編集欄 2 / 2: UPDATE・OTHERお知らせ =====
// 既存アプリの更新はUPDATE、サービス公開以外の告知はOTHERとして、
// PROJECT-CARD-RULES.mdの「お知らせ入力テンプレート」を使って1件追加します。
// RELEASEはここへ手入力しません。
const manualNews = [
  {date:'2026.09.04',tag:'UPDATE',title:{ja:'Fcam pro v2.0.0 を公開しました。',en:'Fcam pro v2.0.0 is available.',zh:'Fcam pro v2.0.0 已发布。',pt:'Fcam pro v2.0.0 está disponível.'},summary:{ja:'操作パネルを画面に合わせて作り直しました。スマホ縦は従来の縦積み、大きめの端末の縦は左に浮くパネル（アイコン2列・縦タブ・上/中央/下寄せ）、横向きは右のサイドバー。パネルは下部のボタンで開閉でき、閉じるとシャッター・前後切替・バッテリー残量だけの小さな島になり、ドラッグで動かせます。前後カメラの切替はシャッターの横に、最新の撮影サムネイルはパネル下部に置き、タップで標準ギャラリーへ。マニュアルパネルからシャッター音量スライダーを外し、マニュアル設定ボタンは写真・動画モードだけに表示。アイコンも新しくしました。',en:'The control panel is rebuilt to fit the screen: phone-portrait keeps the stacked layout, a larger portrait screen shows a floating left panel (two-column icons, vertical tabs, top/center/bottom alignment), and landscape shows a right side-rail. The panel collapses from a bottom button into a small movable island with just the shutter, front/back switch and battery level. Front/back is now next to the shutter, and the latest-capture thumbnail sits at the bottom of the panel and opens the system gallery. The shutter-volume slider is gone from the manual panel, and the manual-settings button only shows in photo and video mode. New app icon.',zh:'操作面板按屏幕重建：手机竖屏保持叠放布局，大屏竖屏显示悬浮的左侧面板（图标两列、纵向标签、上/中/下对齐），横屏显示右侧栏。面板可由底部按钮折叠，折叠后只剩快门、前后摄像头切换和电量的小浮岛，可拖动。前后切换移到快门旁边，最新拍摄缩略图置于面板底部，点按进入系统相册。手动面板去掉了快门音量滑块，手动设置按钮只在照片和视频模式显示。更换了应用图标。',pt:'O painel de controles foi refeito para caber na tela: no celular em retrato mantém o layout empilhado, uma tela de retrato maior mostra um painel flutuante à esquerda (ícones em duas colunas, abas verticais, alinhamento topo/centro/base) e em paisagem mostra uma barra à direita. O painel recolhe por um botão inferior para uma pequena ilha móvel com apenas o obturador, a troca frontal/traseira e o nível de bateria. A troca frontal/traseira agora fica ao lado do obturador e a miniatura da última captura fica na base do painel e abre a galeria do sistema. O controle de volume do obturador saiu do painel manual e o botão de ajustes manuais só aparece nos modos foto e vídeo. Novo ícone do app.'},url:'https://studio-rizi.pages.dev/projects/fcam-pro/'},
  {date:'2026.09.03',tag:'UPDATE',title:{ja:'WAKARU v0.0.4 を公開しました。',en:'WAKARU v0.0.4 is available.',zh:'WAKARU v0.0.4 已发布。',pt:'WAKARU v0.0.4 está disponível.'},summary:{ja:'テキスト層のないスキャンPDFのページと、文字のある画像を OCR して検索対象に加えます（純Rustエンジン、モデルは初回のみ取得）。スキャンPDFには元の座標に合わせた不可視テキスト層付きの検索可能PDFも生成します。Studio には、見出しと本文の構成だけを渡すと Markdown・Word・PDF の体裁を整えて出力する build_document ツールを追加しました。現在は招待制配布です。',en:'Scanned PDF pages with no text layer and images that contain text are now OCR’d and made searchable (a pure-Rust engine; models fetched once). A scanned PDF also gets a searchable copy with an invisible, position-matched text layer. Studio gains a build_document tool that turns a title and sections into a formatted Markdown, Word or PDF document. Distribution is currently invite-only.',zh:'现在会对没有文字层的扫描版 PDF 页面以及含文字的图片进行 OCR 并纳入检索（纯 Rust 引擎，模型仅首次下载）。扫描版 PDF 还会生成带有位置对齐的隐形文字层的可搜索副本。Studio 新增 build_document 工具，只需提供标题与分节即可输出排版好的 Markdown、Word 或 PDF。目前为邀请制分发。',pt:'Páginas de PDF digitalizado sem camada de texto e imagens com texto agora passam por OCR e entram na busca (motor em Rust puro; modelos baixados uma vez). Um PDF digitalizado também ganha uma cópia pesquisável com camada de texto invisível alinhada. O Studio ganha a ferramenta build_document, que transforma um título e seções em um documento formatado em Markdown, Word ou PDF. A distribuição é atualmente por convite.'},url:'https://studio-rizi.pages.dev/projects/wakaru/'},
  {date:'2026.09.03',tag:'UPDATE',title:{ja:'WAKARU v0.0.3 を公開しました。',en:'WAKARU v0.0.3 is available.',zh:'WAKARU v0.0.3 已发布。',pt:'WAKARU v0.0.3 está disponível.'},summary:{ja:'ローカルネットワーク上のAI（LM Studio・Ollama・LANの推論サーバー）への接続をシステムプロキシに邪魔されず直接行えるよう修正し、macOSのローカルネットワーク許可に対応、接続テストの失敗理由も具体的に表示します。UIは広い画面での偏りを解消して中央寄せ・可変幅にし、暗いテーマのコントラストを強化、全体をmacOSネイティブ風の見た目に整えました。あわせて本体ソースコードをMITで公開しました。',en:'Local-network AI connections (LM Studio, Ollama, a LAN inference server) now bypass the system proxy and connect directly, macOS Local Network access is declared, and a failed connection test names the actual cause. The layout centres on wide screens instead of pinning to one edge, the dark theme has stronger contrast, and the whole app now reads as native macOS. The application source is also now public under MIT.',zh:'现在连接局域网中的 AI（LM Studio、Ollama、LAN 推理服务器）会绕过系统代理直接连接，已声明 macOS 本地网络访问权限，连接测试失败时也会说明具体原因。界面在宽屏上不再偏向一侧，改为居中、可变宽度，深色主题对比度增强，整体呈现原生 macOS 观感。应用源代码亦已按 MIT 许可开源。',pt:'As conexões de IA na rede local (LM Studio, Ollama, um servidor de inferência na LAN) agora ignoram o proxy do sistema e conectam diretamente, o acesso à Rede Local do macOS é declarado, e um teste de conexão com falha indica a causa real. O layout se centraliza em telas largas em vez de ficar preso a uma borda, o tema escuro tem mais contraste e todo o app agora parece nativo do macOS. O código-fonte do aplicativo também passou a ser público sob a licença MIT.'},url:'https://studio-rizi.pages.dev/projects/wakaru/'},
  {date:'2026.09.02',tag:'UPDATE',title:{ja:'MLXBar v1.9.1 を公開しました。',en:'MLXBar v1.9.1 is available.',zh:'MLXBar v1.9.1 已发布。',pt:'MLXBar v1.9.1 está disponível.'},summary:{ja:'OpenAI互換APIの細かな不具合を修正しました。1回の応答にツール呼び出しが2つ以上あるストリームで識別情報が重複する問題、ツールを使わない非ストリーム応答で推論モデルの思考内容が返らず消えていた問題（本文には出さず専用フィールドで返すよう修正）、一部の入力でストリームが途中終了しうる問題です。',en:"Small OpenAI-compatible API fixes: a duplicated role marker in streams with two or more tool calls in one response, a reasoning model's thinking text being dropped instead of returned on non-streaming tool-less replies (now returned in its own field, never in the body), and a malformed input that could cut a stream short.",zh:'修复了 OpenAI 兼容 API 的一些小问题：单次响应包含两个及以上工具调用的流式输出中角色标记重复、不使用工具的非流式响应中推理模型的思考内容被丢弃而非返回（现改为在专用字段返回，绝不进入正文）、以及某些异常输入可能导致流提前结束的问题。',pt:'Pequenas correções na API compatível com OpenAI: marcador de papel duplicado em streams com duas ou mais chamadas de ferramenta numa resposta, o texto de raciocínio de um modelo sendo descartado em vez de retornado em respostas não-streaming sem ferramentas (agora retornado em campo próprio, nunca no corpo) e uma entrada malformada que podia encerrar um stream antes da hora.'},url:'https://studio-rizi.pages.dev/projects/mlx-bar/'},
  {date:'2026.09.02',tag:'UPDATE',title:{ja:'WAKARU v0.0.2 を公開しました。',en:'WAKARU v0.0.2 is available.',zh:'WAKARU v0.0.2 已发布。',pt:'WAKARU v0.0.2 está disponível.'},summary:{ja:'PDF・Word・PowerPoint・表計算などを実際のレイアウトで閲覧できるViewer、ローカル意味検索、画像Vision、Studioの進行表示、Streamable HTTP MCP、Silero音声検出を追加しました。',en:'Documents now render in format-aware PDF, Word, PowerPoint and spreadsheet viewers, alongside local semantic search, image Vision, live Studio progress, Streamable HTTP MCP and Silero speech detection.',zh:'新增按格式渲染 PDF、Word、PowerPoint 与表格的查看器，并加入本地语义检索、图片 Vision、Studio 实时进度、Streamable HTTP MCP 和 Silero 语音检测。',pt:'Documentos agora são exibidos em visualizadores próprios para PDF, Word, PowerPoint e planilhas, com busca semântica local, Vision para imagens, progresso do Studio, MCP Streamable HTTP e detecção de voz Silero.'},url:'https://studio-rizi.pages.dev/projects/wakaru/'},
  {date:'2026.09.02',tag:'UPDATE',title:{ja:'WAKARU v0.0.1 を公開しました。',en:'WAKARU v0.0.1 is available.',zh:'WAKARU v0.0.1 已发布。',pt:'WAKARU v0.0.1 está disponível.'},summary:{ja:'狭い縦画面や低い横画面でも欠けないUIへ修正し、LAN上のOpenAI・Anthropic互換API設定とローカルstdio MCP接続を強化しました。',en:'The UI now fits narrow portrait and low landscape windows, with stronger LAN OpenAI/Anthropic-compatible API setup and local stdio MCP support.',zh:'界面现可适配窄竖屏与低高度横屏，并强化了局域网 OpenAI/Anthropic 兼容 API 设置及本地 stdio MCP 支持。',pt:'A interface agora se adapta a janelas estreitas ou baixas, com configuração reforçada de APIs OpenAI/Anthropic na LAN e suporte a MCP stdio local.'},url:'https://studio-rizi.pages.dev/projects/wakaru/'},
  {date:'2026.09.01',tag:'UPDATE',title:{ja:'WAKARU v0.0.0 資料処理とダークUIを更新。',en:'WAKARU v0.0.0 improves document safety and dark UI.',zh:'WAKARU v0.0.0 改进资料安全与深色界面。',pt:'WAKARU v0.0.0 melhora documentos e interface escura.'},summary:{ja:'資料本文をAIのシステム指示から分離し、小型モデル向けの確認・文書保存手順、短すぎるMarkdownの保存防止、ダークテーマの白い主要文字を追加しました。',en:'Source text is now separated from system instructions, with a smaller-model verify-and-write workflow, protection against saving overly shortened Markdown, and exact-white primary text in dark mode.',zh:'资料正文现与系统指令分离，并加入适合较小模型的核对与写入流程、过短 Markdown 保存防护，以及深色模式的纯白主要文字。',pt:'O texto-fonte agora fica separado das instruções do sistema, com fluxo de verificação e gravação para modelos menores, bloqueio de Markdown curto demais e texto principal branco no modo escuro.'},url:'https://studio-rizi.pages.dev/projects/wakaru/'},
  {date:'2026.08.31',tag:'UPDATE',title:{ja:'MLXBar v1.9.0 を公開しました。',en:'MLXBar v1.9.0 is available.',zh:'MLXBar v1.9.0 已发布。',pt:'MLXBar v1.9.0 está disponível.'},summary:{ja:'常駐モデルを1つずつアンロードできるようにし、複数モデルの生成中はモデルごとのトークン速度をメニューバーに表示するようにしました。Anthropic・OpenAI互換APIの互換性も精査しています。',en:"You can now unload resident models one at a time, and the menu bar shows each model's token rate while several models generate. The Anthropic- and OpenAI-compatible APIs were also audited for compatibility.",zh:'现在可以逐个卸载常驻模型，多个模型生成时菜单栏会分别显示每个模型的令牌速度。同时审查了 Anthropic 与 OpenAI 兼容 API 的兼容性。',pt:'Agora você pode descarregar modelos residentes um a um, e a barra de menus mostra a taxa de tokens de cada modelo enquanto vários geram. As APIs compatíveis com Anthropic e OpenAI também foram auditadas quanto à compatibilidade.'},url:'https://studio-rizi.pages.dev/projects/mlx-bar/'},
  {date:'2026.08.31',tag:'UPDATE',title:{ja:'MLXBar v1.8.4 を公開しました。',en:'MLXBar v1.8.4 is available.',zh:'MLXBar v1.8.4 已发布。',pt:'MLXBar v1.8.4 está disponível.'},summary:{ja:'ツールを使わないリクエストで、推論対応モデルの思考（thinking）の途中経過が返答本文に混ざることがある不具合を修正しました。',en:"Fixed a bug where a reasoning model's thinking text could leak into the reply body on requests that use no tools.",zh:'修复了在不使用工具的请求中，推理模型的思考过程可能混入回复正文的问题。',pt:'Corrigido um bug em que o texto de raciocínio de um modelo podia vazar para o corpo da resposta em requisições sem ferramentas.'},url:'https://studio-rizi.pages.dev/projects/mlx-bar/'},
  {date:'2026.08.30',tag:'UPDATE',title:{ja:'MLXBar v1.8.1 を公開しました。',en:'MLXBar v1.8.1 is available.',zh:'MLXBar v1.8.1 已发布。',pt:'MLXBar v1.8.1 está disponível.'},summary:{ja:'GUIでできる操作を、すべて同梱のコマンドラインツール mlxbarctl からも行えるようにしました。プロンプトキャッシュの操作、複数モデル常駐の設定、各種トグルに専用コマンドを追加しています。',en:'Everything you can do in the GUI is now available from the bundled mlxbarctl command-line tool, with dedicated commands for prompt-cache actions, model-residency settings, and the various toggles.',zh:'现在 GUI 中的所有操作都可以通过内置的 mlxbarctl 命令行工具完成，并为提示词缓存操作、多模型常驻设置和各类开关新增了专用命令。',pt:'Tudo o que você faz na interface gráfica agora está disponível na ferramenta de linha de comando mlxbarctl incluída, com comandos dedicados para o cache de prompts, os ajustes de residência de modelos e as várias opções.'},url:'https://studio-rizi.pages.dev/projects/mlx-bar/'},
  {date:'2026.08.30',tag:'UPDATE',title:{ja:'MLXBar v1.8.0 を公開しました。',en:'MLXBar v1.8.0 is available.',zh:'MLXBar v1.8.0 已发布。',pt:'MLXBar v1.8.0 está disponível.'},summary:{ja:'同じモデルを複数のプロセスで常駐させ、同一モデルへの生成を並列で処理できるようになりました。Claude Code から使える Anthropic 互換 API（/anthropic）も追加しています。',en:'The same model can now run in several processes so requests to one model generate in parallel, and there is a new Anthropic-compatible API (/anthropic) for use with Claude Code.',zh:'现在同一模型可在多个进程中常驻，对同一模型的生成可并行处理，并新增可供 Claude Code 使用的 Anthropic 兼容 API（/anthropic）。',pt:'O mesmo modelo agora pode rodar em vários processos, então pedidos a um modelo geram em paralelo, e há uma nova API compatível com a Anthropic (/anthropic) para uso com o Claude Code.'},url:'https://studio-rizi.pages.dev/projects/mlx-bar/'},
  {date:'2026.08.30',tag:'UPDATE',title:{ja:'MCS Manager v1.1.0 を公開しました。',en:'MCS Manager v1.1.0 is available.',zh:'MCS Manager v1.1.0 已发布。',pt:'MCS Manager v1.1.0 está disponível.'},summary:{ja:'Forge / NeoForge サーバーの参加プレイヤーを正しく認識するようにしました。内蔵Web管理画面の「ユーザー」タブでも、アプリと同じように OP と BAN を操作できます。',en:'Online-player detection now works on Forge and NeoForge servers, and the built-in Web dashboard manages operators and bans alongside the whitelist, matching the native app.',zh:'现已正确识别 Forge / NeoForge 服务器上的在线玩家，内置 Web 管理界面也能像应用一样管理 OP 和封禁。',pt:'A detecção de jogadores agora funciona em servidores Forge e NeoForge, e o painel Web integrado gerencia operadores e banimentos como o app nativo.'},url:'https://studio-rizi.pages.dev/projects/mcs-manager/'},
  {date:'2026.08.29',tag:'UPDATE',title:{ja:'MLXBar v1.7.1 を公開しました。',en:'MLXBar v1.7.1 is available.',zh:'MLXBar v1.7.1 已发布。',pt:'MLXBar v1.7.1 está disponível.'},summary:{ja:'メニューバーに常駐中のモデルをすべて表示し、エラー表示を選択した言語に統一しました。Zed・Cline・OpenCode などのOpenAI互換クライアントとの接続も改善しています。',en:'The menu bar now lists every resident model, error messages follow the chosen language, and connecting from OpenAI-compatible clients such as Zed, Cline, and OpenCode works more smoothly.',zh:'菜单栏现在会列出所有常驻模型，错误信息会按所选语言显示，并改进了与 Zed、Cline、OpenCode 等 OpenAI 兼容客户端的连接。',pt:'A barra de menus agora lista todos os modelos residentes, as mensagens de erro seguem o idioma escolhido e a conexão a partir de clientes compatíveis com OpenAI como Zed, Cline e OpenCode ficou mais suave.'},url:'https://studio-rizi.pages.dev/projects/mlx-bar/'},
  {date:'2026.08.28',tag:'UPDATE',title:{ja:'MLXBar v1.7.0 を公開しました。',en:'MLXBar v1.7.0 is available.',zh:'MLXBar v1.7.0 已发布。',pt:'MLXBar v1.7.0 está disponível.'},summary:{ja:'別々の常駐モデルを同時に生成できるようになりました。同一モデルへの要求は従来どおり順番に処理します。',en:'Different resident models can now generate at the same time; requests to the same model are still handled in order.',zh:'现在不同的常驻模型可以同时生成；对同一模型的请求仍按顺序处理。',pt:'Modelos residentes diferentes agora podem gerar ao mesmo tempo; pedidos ao mesmo modelo continuam sendo atendidos em ordem.'},url:'https://studio-rizi.pages.dev/projects/mlx-bar/'},
  {date:'2026.08.27',tag:'UPDATE',title:{ja:'Media Master v0.2.0 を公開しました。',en:'Media Master v0.2.0 is available.',zh:'Media Master v0.2.0 已发布。',pt:'Media Master v0.2.0 está disponível.'},summary:{ja:'DeXの誤判定を解消し、全ストレージの表示、PDF・Office文書の検出、スキャンの複数JPG書き出しに対応しました。',en:'Fixed false DeX detection and added full storage browsing, PDF and office-document discovery, and multi-page JPG scan export.',zh:'修复了 DeX 误判，并新增完整存储浏览、PDF 与 Office 文档检测以及多页 JPG 扫描导出。',pt:'Corrige a detecção incorreta do DeX e adiciona navegação completa no armazenamento, detecção de PDFs e documentos do Office e exportação de digitalizações em JPG.'},url:'https://studio-rizi.pages.dev/projects/media-master/'},
  {date:'2026.08.24',tag:'UPDATE',title:{ja:'MLXBar v1.6.2 を公開しました。',en:'MLXBar v1.6.2 is available.',zh:'MLXBar v1.6.2 已发布。',pt:'MLXBar v1.6.2 está disponível.'},summary:{ja:'モデル単位と全体のメモリ上限を守りながら、APIが要求した複数モデルを常駐できるようになりました。',en:'API-requested models can now stay resident together under per-model and aggregate memory limits.',zh:'现在可在单模型与总内存限制下，同时保持 API 请求的多个模型。',pt:'Modelos pedidos pela API agora podem permanecer carregados juntos, com limites de memória por modelo e no total.'},url:'https://studio-rizi.pages.dev/projects/mlx-bar/'},
  {date:'2026.08.23',tag:'UPDATE',title:{ja:'MLXBar v1.6.1 を公開しました。',en:'MLXBar v1.6.1 is available.',zh:'MLXBar v1.6.1 已发布。',pt:'MLXBar v1.6.1 está disponível.'},summary:{ja:'枝分かれした会話のプロンプト再利用が、対象のモデルで実際に有効になりました。',en:'Prompt reuse across branching conversations now actually engages on the models it was built for.',zh:'分支对话的提示词复用现已在目标模型上真正生效。',pt:'A reutilização de prompt em conversas ramificadas agora funciona de fato nos modelos previstos.'},url:'https://studio-rizi.pages.dev/projects/mlx-bar/'},
  {date:'2026.08.23',tag:'UPDATE',title:{ja:'MLXBar v1.6.0 を公開しました。',en:'MLXBar v1.6.0 is available.',zh:'MLXBar v1.6.0 已发布。',pt:'MLXBar v1.6.0 está disponível.'},summary:{ja:'生成を途中で止めても、そこまでの計算を保持して次のターンから再開できるようになりました。',en:'Cancelling a generation now keeps the work already done, so the next turn resumes instead of starting over.',zh:'现在中断生成也会保留已完成的计算，下一轮可继续而无需从头开始。',pt:'Cancelar uma geração agora preserva o trabalho já feito, e o turno seguinte continua em vez de recomeçar.'},url:'https://studio-rizi.pages.dev/projects/mlx-bar/'},
  {date:'2026.08.22',tag:'UPDATE',title:{ja:'Tango pro v2.1.0 を公開しました。',en:'Tango pro v2.1.0 is available.',zh:'Tango pro v2.1.0 已发布。',pt:'Tango pro v2.1.0 está disponível.'},summary:{ja:'学習画面の配置モードと、範囲指定時の進捗バーを追加しました。',en:'Added a quiz layout mode and a progress bar for range-limited study.',zh:'新增学习画面排布模式与范围学习进度条。',pt:'Adicionado um modo de layout de estudo e barra de progresso por intervalo.'},url:'https://studio-rizi.pages.dev/projects/tango-pro/'},
  {date:'2026.08.19',tag:'OTHER',title:{ja:'公式ポートフォリオを公開しました。',en:'The official portfolio is now live.',zh:'官方作品集网站已上线。',pt:'O portfólio oficial já está no ar.'},summary:{ja:'制作したアプリ、記事、プロフィールを一つの場所から見られる公式サイトを公開しました。',en:'A new home for my apps, articles, updates, and profile.',zh:'在一个网站中浏览我开发的应用、文章、动态与个人资料。',pt:'Um novo espaço para meus apps, artigos, novidades e perfil.'}},
  {date:'2026.08.18',tag:'UPDATE',title:{ja:'Volume Routine v1.1.0 を公開しました。',en:'Volume Routine v1.1.0 is available.',zh:'Volume Routine v1.1.0 已发布。',pt:'Volume Routine v1.1.0 está disponível.'},summary:{ja:'時間とWi-FiをきっかけにAndroidの音量を自動調整する最新版です。',en:'The latest release automates Android volume using time and Wi-Fi triggers.',zh:'通过时间与 Wi-Fi 条件自动调整 Android 音量。',pt:'Automatiza o volume do Android usando horário e Wi-Fi.'},url:'https://studio-rizi.pages.dev/projects/volume-routine/'},
  {date:'2026.08.15',tag:'OTHER',title:{ja:'WAKARUの公式ページを公開しました。',en:'The WAKARU website is now live.',zh:'WAKARU 官方网站已上线。',pt:'O site oficial do WAKARU já está no ar.'},summary:{ja:'PDFや音声、動画などの資料を、根拠つきで理解するためのローカルAIアシスタントです。',en:'A local AI assistant for understanding PDFs, audio, video, and more with citations.',zh:'借助本地 AI 和引用依据理解 PDF、音频、视频等资料。',pt:'Assistente local de IA para entender PDFs, áudio e vídeo com citações.'},url:'https://studio-rizi.pages.dev/projects/wakaru/'},
  {date:'2026.08.12',tag:'UPDATE',title:{ja:'Tango pro v2.0.0 を公開しました。',en:'Tango pro v2.0.0 is available.',zh:'Tango pro v2.0.0 已发布。',pt:'Tango pro v2.0.0 está disponível.'},summary:{ja:'CSVから単語帳を作り、4択とタイピングで学べるAndroid・macOSアプリです。',en:'Build vocabulary books from CSV and study with multiple choice or typing.',zh:'从 CSV 创建单词本，并通过选择题或输入练习学习。',pt:'Crie vocabulários via CSV e estude com alternativas ou digitação.'},url:'https://studio-rizi.pages.dev/projects/tango-pro/'}
];

// ===== 以下は自動処理: 通常は編集しません =====
const projectReleaseNews = projects.filter(project => project.announceRelease === true && project.releaseDate).map(project => {
  const releasedName = `${project.name}${project.releaseVersion ? ` ${project.releaseVersion}` : ''}`;
  return {
    date: project.releaseDate,
    tag: 'RELEASE',
    projectCode: project.code,
    title: {
      ja: `${releasedName} を公開しました。`,
      en: `${releasedName} is now available.`,
      zh: `${releasedName} 已发布。`,
      pt: `${releasedName} está disponível.`
    },
    summary: project.description,
    url: project.url
  };
});

window.SITE_CONTENT = {
  projects,
  news: [...manualNews, ...projectReleaseNews].sort((a,b) => b.date.localeCompare(a.date))
};
